{"name": "Тест: запрос с несуществующим заказом возвращает ошибку", "status": "passed", "attachments": [{"name": "log", "source": "3b257ece-20ca-4097-af9f-bfda7acd9256-attachment.txt", "type": "text/plain"}], "start": 1717679535712, "stop": 1717679536076, "uuid": "c6816403-745f-4fae-b5aa-0ae53a44b1c9", "historyId": "4df8ca3f1fcfc736c88db5a30124b814", "testCaseId": "4df8ca3f1fcfc736c88db5a30124b814", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_with_non_existent_number_order_code_400", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "1796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}