{"name": "Тест: при неправильном передаче id курьера, запрос вернет ощибку", "status": "passed", "description": "Генерирую данные заказа, получаю track заказа. Принимаю заказ курьером, ввожу track заказа и несуществующий id курьера в query-параметры, проверяю код 404, и тело ответа", "attachments": [{"name": "log", "source": "4b17be55-3aef-47cf-aed3-a49502355456-attachment.txt", "type": "text/plain"}], "start": 1717768227215, "stop": 1717768227873, "uuid": "5cd07987-8a00-4c23-ac10-4d50ed456aaf", "historyId": "4da4d9340d85ee194ebcae52b0277a0b", "testCaseId": "4da4d9340d85ee194ebcae52b0277a0b", "fullName": "tests.test_assept_order.TestAsseptOrder#test_assept_order_with_incorrect_query_parameter_id_courier_shows_code_404_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assept_order"}, {"name": "subSuite", "value": "TestAsseptOrder"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "8512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assept_order"}]}