{"name": "Тест: при неправильном передаче id курьера, запрос вернет ощибку", "status": "passed", "description": "Генерирую данные заказа, получаю track заказа. Принимаю заказ курьером, ввожу track заказа и несуществующий id курьера в query-параметры, проверяю код 404, и тело ответа", "attachments": [{"name": "log", "source": "b1ccd2b9-530e-4500-9465-d13cb7d8783c-attachment.txt", "type": "text/plain"}], "start": 1717679522734, "stop": 1717679523476, "uuid": "97b736c1-a826-47c1-9cbe-9f73fd852168", "historyId": "4da4d9340d85ee194ebcae52b0277a0b", "testCaseId": "4da4d9340d85ee194ebcae52b0277a0b", "fullName": "tests.test_assept_order.TestAsseptOrder#test_assept_order_with_incorrect_query_parameter_id_courier_shows_code_404_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assept_order"}, {"name": "subSuite", "value": "TestAsseptOrder"}, {"name": "host", "value": "DESKTOP-USF6L0H"}, {"name": "thread", "value": "1796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assept_order"}]}